version: "3.8"

services:
  pacman-app:
    image: ${{secrets.DOCKER_HUB_USERNAME}}/pacman:latest
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
