name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 12

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/pacman-game:${{ github.sha }} .
    
    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.34.0_Linux-64bit.deb

    - name: Scan Docker image for vulnerabilities
      run: |
        trivy image --exit-code 1 --severity CRITICAL ${{ secrets.DOCKER_HUB_USERNAME }}/pacman-game:${{ github.sha }}

    - name: Push Docker image to Docker Hub
      if: github.ref == 'refs/heads/main' && success()
      run: |
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pacman-game:${{ github.sha }}

    - name: Pull and Run the Docker image locally
      run: |
        docker run -d -p 8080:80 ${{ secrets.DOCKER_HUB_USERNAME }}/pacman-game:${{ github.sha }}
