name: CI/CD Pipeline

# Trigger the workflow on push to the main branch or on a pull request
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the environment in which the job will run (Ubuntu)

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js version 12
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      # Build the Docker image using the Dockerfile in the repo
      - name: Build Docker image
        run: docker build -t pacman-game .

      # Scan the Docker image for critical vulnerabilities using Trivy
      - name: Trivy scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy image --severity CRITICAL pacman-game

      # Log in to Docker Hub and push the image only if the workflow is triggered by a push to the main branch
      - name: Push to Docker Hub
        if: github.event_name == 'push'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag pacman-game ${{ secrets.DOCKER_USERNAME }}/pacman-game:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/pacman-game:latest

      # Install Terraform in the runner environment
      - name: Set up Terraform
        run: |
          sudo apt-get install -y unzip
          curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
          unzip terraform_1.0.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      # Configure AWS credentials for Terraform to use
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Initialize Terraform (downloads providers and sets up the backend)
      - name: Terraform Init
        run: terraform init

      # Apply the Terraform configuration to deploy the infrastructure
      - name: Terraform Apply
        run: terraform apply -auto-approve
