name: Docker CI/CD Pipeline

# Trigger the workflow on push to main branch or on pull requests to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Node.js version 12
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 12

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Build Docker image and tag it
    - name: Build Docker image
      run: |
        # Tag the image with the commit SHA for uniqueness
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/pacman-game:${{ github.sha }} .
        # Tag the image as latest for easy access
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/pacman-game:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/pacman-game:latest

    # 5. Install Trivy for vulnerability scanning
    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.34.0_Linux-64bit.deb

    # 6. Scan Docker image for vulnerabilities
    - name: Scan Docker image for vulnerabilities
      run: |
        trivy image --exit-code 1 --severity CRITICAL ${{ secrets.DOCKER_HUB_USERNAME }}/pacman-game:${{ github.sha }}

    # 7. Log in to Docker Hub using Docker Login Action
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # 8. Push Docker image with commit SHA tag
    - name: Push Docker image with commit SHA tag
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pacman-game:${{ github.sha }}

    # 9. Push Docker image with latest tag
    - name: Push Docker image with latest tag
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pacman-game:latest
